[build-system]
requires = ["maturin>=1.3.2"]
build-backend = "maturin"

[project]
name = "rxml"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
description = "A XML parser for Python written in Rust"


[tool.maturin]
features = ["pyo3/extension-module"]
